server:
  port: 80

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ms-consumer    # 防止 Eureka web页面报错 ，主机服务名称修改
    prefer-ip-address: true     # 访问路径可以显示IP地址，（左下角IP显示）

feign:
  hystrix:
    enabled: true # 启动hystrix熔断降级机制

spring:
  application:
    name: ms-consumer-feign
